/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package infrastructure.api;

import framework.web.error.BadRequest;
import framework.web.error.Unauthorized;
import infrastructure.DynamicMediaHandlerSkeleton;
import infrastructure.MailServerSkeleton;
import infrastructure.TestingUser;
import org.junit.jupiter.api.*;
import framework.db.DbManager;
import server.Config;
import server.infrastructure.DbManagerImpl;
import server.infrastructure.root.api.EventAPI;

import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class EventAPITest {
    private static DbManager db;
    private final Config config = new Config(
            "send_mail", "false"
    );
    private final MailServerSkeleton mail = new MailServerSkeleton();
    private final DynamicMediaHandlerSkeleton media = new DynamicMediaHandlerSkeleton();

    ArrayList<Long> events;
    private final TestingUser o1 = new TestingUser("Organizer", "organizer@gmail.com", "password");
    private final TestingUser u1 = new TestingUser("User", "user@gmail.com", "pass");

    @BeforeAll
    public void setup() throws SQLException, BadRequest, UnknownHostException, Unauthorized {
        db = new DbManagerImpl("event_api_test", true, true, true);
        o1.register(mail, db, config);
        o1.login(mail, db, config);
        o1.makeOrganizer(db, null);

        u1.register(mail, db, config);
        u1.login(mail, db, config);
    }

    @Test
    @Order(1)
    public void createEventTest() throws SQLException, Unauthorized {
        var auth = o1.organizerSession(db, null);
        events = new ArrayList<>();
        try(var trans = db.rw_transaction(null)){
            events.add(EventAPI.create_event(auth, trans));
            trans.tryCommit();
        }
        try(var trans = db.rw_transaction(null)){
            events.add(EventAPI.create_event(auth, trans));
            trans.tryCommit();
        }
        try(var trans = db.rw_transaction(null)){
            events.add(EventAPI.create_event(auth, trans));
            trans.tryCommit();
        }

        auth = u1.userSession(db, null);
        try(var trans = db.rw_transaction(null)){
            events.add(EventAPI.create_event(auth, trans));
            trans.tryCommit();
            Assertions.fail("A regular user cannot create an event");
        }catch (SQLException ignore){}
    }

    @AfterAll
    public void close() {
        db.close();
    }
}
