/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package infrastructure.api;

import framework.web.error.BadRequest;
import framework.web.error.Unauthorized;
import infrastructure.MailServerSkeleton;
import infrastructure.TestingUser;
import org.junit.jupiter.api.*;
import framework.db.DbManager;
import server.infrastructure.DbManagerImpl;
import server.infrastructure.root.api.EventAPI;
import server.infrastructure.root.api.SearchAPI;

import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class SearchAPITest {
    private static DbManager db;
    private final MailServerSkeleton mail = new MailServerSkeleton();

    ArrayList<Long> events;
    private final TestingUser u1 = new TestingUser("User", "user@gmail.com", "pass");
    private final TestingUser o1 = new TestingUser("Organizer", "organizer@gmail.com", "password");

    @BeforeAll
    public void setup() throws SQLException, BadRequest, UnknownHostException, Unauthorized {
        db = new DbManagerImpl("search_api_test", true, true, true);

        // Register the fake users
        u1.register(mail, db, false);
        u1.login(mail, db, false);
        o1.register(mail, db, false);
        o1.login(mail, db, false);
        o1.makeOrganizer(db, null, mail);

        // Create some fake events
        var auth = o1.organizerSession(db, null);
        events = new ArrayList<>();
        try(var trans = db.rw_transaction(null)){
            events.add(EventAPI.create_event(auth, trans));
            trans.tryCommit();
        }
        try(var trans = db.rw_transaction(null)){
            EventAPI.set_draft(auth, trans, events.getLast(), false);
            trans.tryCommit();
        }
        try(var trans = db.rw_transaction(null)){
            events.add(EventAPI.create_event(auth, trans));
            trans.tryCommit();
        }
        try(var trans = db.rw_transaction(null)){
            EventAPI.set_draft(auth, trans, events.getLast(), false);
            trans.tryCommit();
        }
        try(var trans = db.rw_transaction(null)){
            events.add(EventAPI.create_event(auth, trans));
            trans.tryCommit();
        }
        try(var trans = db.rw_transaction(null)){
            EventAPI.set_draft(auth, trans, events.getLast(), false);
            trans.tryCommit();
        }
        System.out.println("\t\033[33;1m" + events.size() + " \033[0mfake events were made");
    }

    @Test
    @Order(1)
    public void searchEventsTest() throws SQLException, Unauthorized {
        var session = u1.userSession(db, null);

        // Get all events that were made
        try(var trans = db.ro_transaction(null)) {
            SearchAPI.Search s = new SearchAPI.Search(
                    null, null, null, null,
                    null, null,null, null, null,
                    null,
                    null, null,null, null,
                    null,null, null, null, SearchAPI.SortBy.Nothing
                    );
            List<EventAPI.Event> result = SearchAPI.search_events(session, trans, s, false);
            System.out.println("\t\033[33;1m" + result.size() + "\033[0m events found while searching for all");
        }
    }

    @AfterAll
    public static void close() {
        db.close();
    }
}
